server.port: 8080


spring:
  redis:
    database: 0
    host: ext-a.kubesail.io
    port: 35882
    password:
    timeout: 10_000
  datasource:
    # 数据库连接信息
    platform: h2
    url: jdbc:h2:mem:demo
    ##  url: jdbc:h2:file:E:/H2/demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
#    data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

order:
  name: 显卡
  list:
    - GTX 2060
    - GTX 2080Ti
    - GTX 3080
  maps:
    CPU: 10400f散
    zhuban: 微星b460M迫击炮
    neicun: 英睿达8G*2 c9bjz ddr4 3000频率
    xianshiqi: 宏碁EG240YP显示器
    dianyuan: 航嘉HYPER金牌全模组650w电源
    yingpan: 蓝盘SN550 500G固态+1T机械
    jixiang: 航嘉GS500C机箱
    散热: 玄冰400
