server.port: 8080

order:
  name: 主机
  list:
    - GTX 750
    - GTX 960
    - GTX 1080
  maps:
    CPU: i3-10100F
    主板: 昂达H410
    内存: 威刚DDR4 2666 8GX2
    显卡: 索泰GTX1070 8G
    电源: 航嘉额定500W
    固态: 台酷256G M.2
    机械: 西数1T机械
    机箱: 航嘉GS500
    散热器: 安钛克战虎a30
    显示器: 24寸 AOC 24G2
