

spring:
  redis:
    database: 0
    host: ext-a.kubesail.io
    port: 35882
    password:
    timeout: 10_000
    datasource:
      # 数据库连接信息
      url: jdbc:mysql://ext-a.kubesail.io:42964/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      # 数据库用户名
      username: root
      # 数据库密码
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        connection-timeout: 30000
        maximum-pool-size: 20
        max-lifetime: 1800000
        minimum-idle: 5
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      database: MySQL
      openInView: false
      show_sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
  flyway:
    enable: false
    locations: classpath:db/migration/mysql

  order:
    name: 显卡
    list:
      - GTX 2060
      - GTX 2080Ti
      - GTX 3080
    maps:
      CPU: 10400f散
      zhuban: 微星b460M迫击炮
      neicun: 英睿达8G*2 c9bjz ddr4 3000频率
      xianshiqi: 宏碁EG240YP显示器
      dianyuan: 航嘉HYPER金牌全模组650w电源
      yingpan: 蓝盘SN550 500G固态+1T机械
      jixiang: 航嘉GS500C机箱
      散热: 玄冰400


order:
  name: 主机
  list:
    - GTX 750
    - GTX 960
    - GTX 1080
  maps:
    CPU: i3-10100F
    主板: 昂达H410
    内存: 威刚DDR4 2666 8GX2
    显卡: 索泰GTX1070 8G
    电源: 航嘉额定500W
    固态: 台酷256G M.2
    机械: 西数1T机械
    机箱: 航嘉GS500
    散热器: 安钛克战虎a30
    显示器: 24寸 AOC 24G2
