server.port: 8080

order:
  name: 显卡
  list:
    - GTX 2060
    - GTX 2080Ti
    - GTX 3080
  maps:
    CPU: 10400f散
    zhuban: 微星b460M迫击炮
    neicun: 英睿达8G*2 c9bjz ddr4 3000频率
    xianshiqi: 宏碁EG240YP显示器
    dianyuan: 航嘉HYPER金牌全模组650w电源
    yingpan: 蓝盘SN550 500G固态+1T机械
    jixiang: 航嘉GS500C机箱
    散热: 玄冰400
